# 环境 dev / test / product
active: dev
domain: demo.com
scheme: http
port: 8080
sock: /tmp/go.sock

swagger:
  port: 9090

# 存储方案二选一， mysql or sqlite3
storage-driver: mysql

mysql:
  master:
    user: root
    password: password
    host: 127.0.0.1
    port: 3306
    database: demo
    charset: utf8mb4
    timezone: Asia/Shanghai
  slave1:
    user: root
    password: password
    host: 127.0.0.1
    port: 3307
    database: demo
    charset: utf8mb4
    timezone: Asia/Shanghai

sqlite:
  storageFile: /tmp/sqlite3.db
  timezone: Asia/Shanghai

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

es:
  - http://localhost:9200
