# 环境 dev / test / product
active: dev

# 域名端口服务，可单独提供服务
domain: localhost
scheme: http
port: 8080

# socket 方式，结合nginx转发
sock: /tmp/go.sock

# 时区
timezone: Asia/Shanghai

swagger:
  port: 9090

# mysql
mysql:
  master:
    user: root
    password: password
    host: 127.0.0.1
    port: 3306
    database: demo
    charset: utf8mb4
  slave1:
    user: root
    password: password
    host: 127.0.0.1
    port: 3307
    database: demo
    charset: utf8mb4

# sqlite
sqlite:
  storageFile: /tmp/sqlite3.db
  timezone: Asia/Shanghai

# redis
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

# elasticsearch
es:
  - http://localhost:9200

# minio
minio:
  endpoint: "127.0.0.1:9000"
  access_key_id: "testtest"
  secret_access_key: "testtest"
  use_ssl: false
